services:
  app:
    image: ghcr.io/muffn/laravel-demo:latest
    container_name: meetkat
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - APP_KEY=${APP_KEY}
    volumes:
      - app-database:/var/www/html/database

volumes:
  app-database:
